### ISSUE TITLE
Catalog Of My Things Kanban board

### ISSUE THREAD

**Issue by Miliyonayalew** [MarcoOquendoC/CatalogOfMyThings-RubyCapstone#31]
## In this Milestone We @MarcoOquendoC,  @Miliyonayalew and @limavfabio 

Setup the Kanban Board based on the group task divided requirements, Below please find the kanban board link
[Kanban Board Project link](https://github.com/MarcoOquendoC/CatalogOfMyThings-RubyCapstone/projects/1)
 
This is a **3-member** team and tasks were assigned as follows:
  - `Team Member #1` @limavfabio 
  - `Team Member #2` @MarcoOquendoC 
  - `Team Member #3` @Miliyonayalew

**Comment by Davidosky007** [comment]
Hi @Miliyonayalew @limavfabio @MarcoOquendoC 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
## Highlights
* Well written issue description 👍 
* All member info provided 👍 
* Link to Kanban board working 👍 

## Required Changes ♻️
*  Kindly ensure that all team members have equally distributed point at least not more than >= 5 points difference 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MarcoOquendoC** [comment]
# Thank you @Davidosky007 

## The kanban board points (pt) have been redistributed.

### Group tasks take equally distributed points:
- [1pt] Create Item class `#1`
- [1pt] Add methods to Item class. `#3`
- [1pt] Create a main.rb `#4`
- [2pt] Implement startup actions. `#18`

### Miliyon's tasks:
- [1pt] Create a Game Class `#6`
- [1pt] Create an Author Class `#5`
- [2pt] Implement methods in the Author Class `#9`
- [2pt] Add unit tests for Author methods `#15`
- [2pt] Implement author and game options `#21`
- [2pt] Preserve Game and Author data in .json files `#19`
- [1pt] Create a schema.sql for Games and authors table `#17`

### Fábio's tasks:
- [1pt] Create a Label class `#30`
- [1pt] Create Book Class `#2`
- [1pt] Implement method can_be_archived? in the Book class `#8`
- [1pt] Implement add_item method in the Label class `#7`
- [1pt] Add unit tests for Label class `#12`
- [1pt] Add unit tests for Book#can_be_archived? `#11`
- [2pt] Implement options for Book and Label classes `#13`
- [2pt] Preserve data for Book and Label classes `#14`
- [1pt] Create a schema.sql file for Book and Label tables `#16`

### Marco's tasks:
- [1pt] Create Genre.rb file `#24`
- [1pt] Create MusicAlbum.rb file. `#23`
- [2pt] Implement methods for MusicAlbums and Genre classes `#25`
- [2pt] Add unit tests for MusicAlbum and Genre classes `#26`
- [2pt] Add options for Genre and MusicAlbum classes `#27`
- [2pt] Preserve data for Genre and MusicAlbum classes `#28`
- [1pt] Create schema for Genre and MusicAlbum tables `#29`


Total group tasks add up to [5pt]
Each team member tasks add up to [11pt]

### Total project
3 * [11pt] + [5pt] = **[38pt]**

**Comment by Davidosky007** [comment]
Hi @Miliyonayalew @MarcoOquendoC @limavfabio 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![CR GIF](https://user-images.githubusercontent.com/52497246/211417463-1f223770-a137-4ffa-a197-2d223eede1f9.gif)

## Highlights
* All tasks equally distributed 👍 
* Proper team member info provided 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
